import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#fdeae3",
        background: "#FAF6EF",
        secondary: "#286958",
        "on-secondary-container": "#2f6f5e",
        "surface-dim": "#e8d6cf",
        "on-primary-fixed-variant": "#793000",
        "primary-tint": "#F1DFCF",
        "inverse-on-surface": "#ffede6",
        "ink-muted": "#5B564C",
        error: "#B3261E",
        "surface-tint": "#9b4511",
        "secondary-container": "#aef0da",
        surface: "#fff8f6",
        "primary-fixed": "#ffdbcb",
        "outline-variant": "#dcc1b5",
        "on-error": "#ffffff",
        ink: "#211D18",
        "accent-tint": "#DCEAE4",
        "secondary-fixed": "#aef0da",
        "on-secondary-fixed": "#002019",
        "border-strong": "#CBBFA3",
        "on-secondary": "#ffffff",
        "surface-alt": "#F3EDE1",
        "on-surface": "#231a15",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e60",
        "surface-container-low": "#fff1eb",
        "surface-container-highest": "#f1dfd7",
        "secondary-fixed-dim": "#93d3bf",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007f9b",
        "on-primary-fixed": "#341100",
        "surface-container-high": "#f7e4dd",
        "on-tertiary-container": "#fafdff",
        primary: "#97430e",
        "surface-container-lowest": "#ffffff",
        outline: "#897268",
        "info-tint": "#E4ECEF",
        "inverse-surface": "#392e29",
        "inverse-primary": "#ffb692",
        "surface-variant": "#f1dfd7",
        "primary-fixed-dim": "#ffb692",
        "primary-container": "#b75a26",
        "tertiary-fixed": "#b6ebff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#71d3f4",
        "on-surface-variant": "#55433a",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#055141",
        tertiary: "#00657b",
        info: "#4F6D7A",
        warning: "#B5790F",
        "on-tertiary-fixed": "#001f28",
        "primary-dark": "#9C4C21",
        "on-primary-container": "#fffbff",
        "surface-bright": "#fff8f6",
        "on-background": "#231a15",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        sm: "6px",
      },
      spacing: {
        base: "4px",
        "space-lg": "24px",
        "space-sm": "8px",
        "space-xl": "32px",
        "space-2xl": "48px",
        "space-3xl": "64px",
        gutter: "24px",
        "space-md": "16px",
        "space-xs": "4px",
        "max-width": "1120px",
      },
      fontFamily: {
        "text-caption": ["Public Sans", "sans-serif"],
        "text-button": ["Public Sans", "sans-serif"],
        "text-h3": ["Fraunces", "serif"],
        "text-h2": ["Fraunces", "serif"],
        "text-h4": ["Public Sans", "sans-serif"],
        "text-hero-mobile": ["Fraunces", "serif"],
        "text-body-lg": ["Public Sans", "sans-serif"],
        "text-h1-mobile": ["Fraunces", "serif"],
        "text-body": ["Public Sans", "sans-serif"],
        "text-mono": ["IBM Plex Mono", "monospace"],
        "text-h1": ["Fraunces", "serif"],
        "text-hero": ["Fraunces", "serif"],
      },
    },
  },
  plugins: [],
};

export default config;
